### ISSUE TITLE
Stopwatch.lua - no option to start stopwatch

### ISSUE THREAD

**Issue by raleighlittles** [midnight-studios/obs-lua#11]
Using:

* Windows 10
* OBS 30.0.2
* Latest version of `stopwatch.lua`

I looked at the tutorials posted and it shows a "Start Stopwatch" button present after loading the script. However, I don't see this option on my OBS.

Expected: 

![image](https://github.com/midnight-studios/obs-lua/assets/2137201/fc0a3442-df09-42de-81b6-6bb792ed86d5)

What I see:

![image](https://github.com/midnight-studios/obs-lua/assets/2137201/fbddd867-bf57-46d6-9601-64186e06e423)
[2024-01-10 15-46-42.txt](https://github.com/midnight-studios/obs-lua/files/13898415/2024-01-10.15-46-42.txt)

[2024-01-10 15-46-42.txt](https://github.com/midnight-studios/obs-lua/files/13898418/2024-01-10.15-46-42.txt)

Log file attached.

**Comment by midnight-studios** [comment]
In order to fully enable the timer, the the 'timer source' needs to be defined. Please set 'Layout' to 'Advanced' and then 'Timer Settings' to 'Expanded' and then assign 'Timer Source.' I apologise for the confusion on this. I will consider a more intuitive solution or create a tutorial on this in an upcoming video.
