### ISSUE TITLE
Tried to use it today, got an error...

### ISSUE THREAD

**Issue by rodduarte666** [midnight-studios/obs-lua#5]
![image](https://user-images.githubusercontent.com/8533902/172006904-7658c4a9-a95b-44ed-a906-3c4e1376ec99.png)

Help?

**Comment by midnight-studios** [comment]
Some users reported that the Script breaks down when installed with a similar error message produced as the following:

Error loading file: ...lua:7: unexpected symbol near '<'

I can’t exactly tell you why it happens as it appear to be happening due to some missing library or something on windows and it is uncommon.

To resolve the issue, you need to remove the comments from the Script Source code.

You can remove the comments manually yourself, or easily and quickly with [this script here](https://obsproject.com/forum/resources/lua-comment-removal.1443/)
